Add licensing info, support for 64-bits, build txz

diff --git a/libdaemon.SlackBuild b/libdaemon.SlackBuild
--- a/libdaemon.SlackBuild
+++ b/libdaemon.SlackBuild
@@ -1,14 +1,32 @@
 #!/bin/sh
 #
-# SlackBuild for libdaemon
-# Written by Georgi D. Sotirov <gdsotirov@dir.bg>
+# Slackware build script for libdaemon
+# Copyright (C) 2007-2011 Georgi D. Sotirov <gdsotirov@dir.bg>
+#
+# This program is free software; you can redistribute it and/or
+# modify it under the terms of the GNU General Public License
+# as published by the Free Software Foundation; either version 2
+# of the License, or (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+# 
+# You should have received a copy of the GNU General Public License
+# along with this program; if not, write to the Free Software
+# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
+#
+# Visit SlackPack at http://sotirov-bg.net/slackpack/
+#
+# $Id: libdaemon.SlackBuild,v 1.6 2011/10/15 15:25:04 gsotirov Exp $
 #
 
-. ../slack-package.conf
+. ../../slack-package.conf
 
 NAME=libdaemon
 VERSION=0.14
-BUILD=2
+BUILD=${BUILD:-1}
 ARCH=${ARCH:-i486}
 
 CWD=${CWD:-`pwd`}
@@ -33,25 +51,25 @@ mkdir -p $PKG
 
 # Extract the source
 cd $TMP
-tar -zxvf $CWD/$NAME-$VERSION.tar.gz
+tar -xvf $CWD/$NAME-$VERSION.tar.?z* || exit 1
 cd $SRC
 fix_source
 
+# Configure
 CFLAGS=$SLKCFLAGS \
 CXXFLAGS=$SLKCFLAGS \
 ./configure --build=$ARCH-slackware-linux \
             --host=$ARCH-slackware-linux \
             --prefix=/usr \
-	    --enable-shared=yes \
-	    --enable-static=no
+            --libdir=/usr/lib${LIBDIRSUFFIX} \
+            --enable-shared=yes \
+            --enable-static=no || exit 2
 
-make -j4 all || exit 1 
+# Build & install
+make -j4 all || exit 3
+make DESTDIR=$PKG install || exit 4
 
-PKG="$TMP/package-$NAME"
-mkdir -p $PKG
-
-make DESTDIR=$PKG install || exit 2
-
+# Prepare package
 bin_perms $PKG
 ( cd $PKG; strip_lib )
 ( cd $SRC; create_docs $PKG $NAME-$VERSION )
@@ -65,13 +83,15 @@ install -m 644 $CWD/slack-desc       $PKG/usr/src/slackbuilds/$NAME-$VERSION/sla
 install -m 644 $CWD/slack-required   $PKG/usr/src/slackbuilds/$NAME-$VERSION/slack-required
 install -m 644 $CWD/$NAME.SlackBuild $PKG/usr/src/slackbuilds/$NAME-$VERSION/$NAME.SlackBuild
 
+# Assemble
 cd $PKG
 PKGNAME=$NAME-$VERSION-$ARCH-$BUILD$MYIN
-makepkg -l y -c n $PKG_DIR/$PKGNAME.tgz
+makepkg -l y -c n $PKG_DIR/$PKGNAME.txz
 cd $PKG_DIR
-md5sum $PKGNAME.tgz > $PKGNAME.tgz.md5
+md5sum $PKGNAME.txz > $PKGNAME.txz.md5
 cat $PKG/install/slack-desc > $PKG_DIR/$PKGNAME.txt
 
+# Clean up
 if [ "$1" == "--cleanup" ]; then
   rm -r $SRC
   rm -r $PKG
